### ISSUE TITLE
the pretrained net on imagenet

### ISSUE THREAD

**Issue by chenjun2hao** [ydhongHIT/DDRNet#1]
could you upload the pretrained model on imagenet. thanks!

**Comment by ydhongHIT** [comment]
Hi, I have upload the pretrained models on imagenet.

**Comment by ydhongHIT** [comment]
> could you upload the pretrained model on imagenet. thanks!

Hi, I have upload the pretrained models on imagenet.

**Comment by chenjun2hao** [comment]
thanks!
