### ISSUE TITLE
resolution of  segmentation output map

### ISSUE THREAD

**Issue by fjremnav** [ydhongHIT/DDRNet#13]
Is resolution of  segmentation output map 1/8 of input image resolution?
How can I get the same resolution of segmentation output map as the input image resolution?

Thanks,

**Comment by ydhongHIT** [comment]
> Is resolution of segmentation output map 1/8 of input image resolution?
> How can I get the same resolution of segmentation output map as the input image resolution?
> 
> Thanks,
Yes. Set the value of scale_factor to 8 in "class segmenthead".

**Comment by ydhongHIT** [comment]
> Is resolution of segmentation output map 1/8 of input image resolution?
> How can I get the same resolution of segmentation output map as the input image resolution?
> 
> Thanks,

Yes. Set the value of scale_factor to 8 in "class segmenthead".
