### ISSUE TITLE
Question about crop augmentation during training

### ISSUE THREAD

**Issue by mbcel** [ydhongHIT/DDRNet#16]
Thank you very much for your great contribution!

I have a question about the crop augmentation that you used during training. In the paper you say that you cropped the cityscapes images to 1024x1024 during training. Considering this how did you inference on the full resolution images (2048x1024) to get the benchmark results? Did you feed in 2 crops (left and right 1024x1024 crop) into the model with same size as during training and merged both into the full image afterwards or did you feed in the full resolution image during inferencing, although training was done with smaller image crops?

**Comment by ydhongHIT** [comment]
Hi,  I feed in the full resolution image during inference.

**Comment by ydhongHIT** [comment]
> Thank you very much for your great contribution!
> 
> I have a question about the crop augmentation that you used during training. In the paper you say that you cropped the cityscapes images to 1024x1024 during training. Considering this how did you inference on the full resolution images (2048x1024) to get the benchmark results? Did you feed in 2 crops (left and right 1024x1024 crop) into the model with same size as during training and merged both into the full image afterwards or did you feed in the full resolution image during inferencing, although training was done with smaller image crops?

Hi, I feed in the full resolution image during inference.

**Comment by mbcel** [comment]
Thank you for the fast reply!
