### ISSUE TITLE
about training code

### ISSUE THREAD

**Issue by whyandbecause** [ydhongHIT/DDRNet#17]
Hi，the third code dosen‘t work on my PC，when will you please upload you whole project？thx

**Comment by ydhongHIT** [comment]
> Hi，the third code dosen‘t work on my PC，when will you please upload you whole project？thx

We will release the whole project until our paper is accepted.

**Comment by bjarnekvae** [comment]
Congratulations with the [publication](https://arxiv.org/pdf/2101.06085v2.pdf)! 

Can you post the training scrips now? :)

**Comment by ydhongHIT** [comment]
> Congratulations with the [publication](https://arxiv.org/pdf/2101.06085v2.pdf)!
> 
> Can you post the training scrips now? :)

Sorry for the late reply. Currently, our paper is not accepted. But there are many resources which can be used to train our model. Paddleseg has also supported the DDRNet now.
