### ISSUE TITLE
Is there a TensorRT implementation

### ISSUE THREAD

**Issue by YLyeliang** [ydhongHIT/DDRNet#2]
Hi, recently I've read the paper, It's an exciting work that achieved the state-of-the-art performance on the cityscape.
First of all, thanks for sharing the work, I wanna know have you ever did its TensorRT version. If did, can you share it?

**Comment by ydhongHIT** [comment]
Sorry, I didn't implement the tensorrt version because the naive inference speed is competitive.

**Comment by ydhongHIT** [comment]
> Hi, recently I've read the paper, It's an exciting work that achieved the state-of-the-art performance on the cityscape.
> First of all, thanks for sharing the work, I wanna know have you ever did its TensorRT version. If did, can you share it?

Sorry, I didn't implement the tensorrt version because the naive inference speed is competitive.

**Comment by zptang1210** [comment]
I tried to use torch2trt (https://github.com/NVIDIA-AI-IOT/torch2trt) to convert the model to tensorRT. This can reduce time consumption significantly. Hope this helps.

**Comment by midasklr** [comment]
here is my c++ ddrnet.tensorrt:https://github.com/midasklr/DDRNet.TensorRT
