### ISSUE TITLE
您好,想請問會公開訓練的code嗎？

### ISSUE THREAD

**Issue by FrankFang0813** [ydhongHIT/DDRNet#20]
@ydhongHIT ,您好,想請問你們會公開訓練的code嗎？想嘗試來訓練自己的訓練集！
謝謝您!!

**Comment by ydhongHIT** [comment]
非常抱歉，由于一些原因我目前无法公开训练代码。论文模型训练是直接基于[HRNet](https://github.com/HRNet/HRNet-Semantic-Segmentation/tree/pytorch-v1.1)

**Comment by ydhongHIT** [comment]
> 

感谢您的关注，非常抱歉，由于一些原因我目前无法公开训练代码。论文模型训练是直接基于[HRNet](https://github.com/HRNet/HRNet-Semantic-Segmentation/tree/pytorch-v1.1)。也有一些第三方的项目可以训练ddrnet，如[DDRNet.pytorch](https://github.com/chenjun2hao/DDRNet.pytorch)、[Segmentation-Pytorch](https://github.com/Deeachain/Segmentation-Pytorch)、[semantic-segmentation](https://github.com/sithu31296/semantic-segmentation)，都实现了不错的效果。
