### ISSUE TITLE
DAPPM + DDRNet slim for small image segmentation input_size (e.g. 128x128 or 256x256)

### ISSUE THREAD

**Issue by tamirDia** [ydhongHIT/DDRNet#21]
What should be the kernel sizes+strides for DAPPM module for small image sizes? and the number of spp planes? 
Thanks :)

**Comment by ydhongHIT** [comment]
> What should be the kernel sizes+strides for DAPPM module for small image sizes? and the number of spp planes? Thanks :)

In the paper, the stride is 2^n and the kernel size is 2^(n+1) + 1. Because the smallest resolution is 1x1, the resolution of feature maps passed into dappm determines the number of branches.
