### ISSUE TITLE
Link for trained models

### ISSUE THREAD

**Issue by rsmeghana8** [ydhongHIT/DDRNet#3]
Is there a googledrive /dropbox /onedrive link available for trained models?

**Comment by ydhongHIT** [comment]
Now, all the pretrained models have a googledrive link.

**Comment by ydhongHIT** [comment]
> Is there a googledrive /dropbox /onedrive link available for trained models?

Now, all the pretrained models have a googledrive link.

**Comment by rsmeghana8** [comment]
Thank you

**Comment by wuxiongni** [comment]
could you share the pretrained models?
