### ISSUE TITLE
可否上传ImageNet预训练的代码

### ISSUE THREAD

**Issue by CuZaoo** [ydhongHIT/DDRNet#30]
你好，我修改了DDRNet网络，因此想重新使用ImageNet进行预训练，但是怕ImageNet预训练这里出现问题导致模型效果受影响
您能否上传一下DDRNet的在ImageNet的预训练代码呢？
谢谢

**Comment by ydhongHIT** [comment]
> 你好，我修改了DDRNet网络，因此想重新使用ImageNet进行预训练，但是怕ImageNet预训练这里出现问题导致模型效果受影响 您能否上传一下DDRNet的在ImageNet的预训练代码呢？ 谢谢

You can refer to this repo https://github.com/Res2Net/Res2Net-ImageNet-Training.
