### ISSUE TITLE
有关训练的问题

### ISSUE THREAD

**Issue by DOVEXQ** [ydhongHIT/DDRNet#32]
您好，看到了您在回复其他人问题的时候说，您是把训练和验证集合成了大的训练集（train+val=2975+500）去训练的，您有没有尝试过仅仅使用原始训练集train(2975)去做训练，我仅使用训练集train，ddrnet_23_silm的miou仅能达到74左右

**Comment by ydhongHIT** [comment]
> 您好，看到了您在回复其他人问题的时候说，您是把训练和验证集合成了大的训练集（train+val=2975+500）去训练的，您有没有尝试过仅仅使用原始训练集train(2975)去做训练，我仅使用训练集train，ddrnet_23_silm的miou仅能达到74左右

多谢关注。把训练集和验证集合在一起训练只是在向cityscapes服务器提交结果时才这样，过去的工作也都是这样做的。在val集上的测试结果都是只用train集训练得到的。另外需要使用我们提供的imagenet预训练模型。

**Comment by myself0816** [comment]
所以说预训练模型应该用imagenet,而不是用small best val?
