### ISSUE TITLE
cityscapes测试集上传问题

### ISSUE THREAD

**Issue by duzijj** [ydhongHIT/DDRNet#34]
我用作者保存的训练好的ddrnet23-slim， 跑了cityscapes测试集，上传到官网，得到的结果是76.38， 而不是77.44， 是我漏掉了什么设置吗？有挺多模型都是这样得不到论文中的精度。

**Comment by ydhongHIT** [comment]
> 我用作者保存的训练好的ddrnet23-slim， 跑了cityscapes测试集，上传到官网，得到的结果是76.38， 而不是77.44， 是我漏掉了什么设置吗？有挺多模型都是这样得不到论文中的精度。

我提供的模型是只在训练集上训练的模型，对应于在评估集上的结果。在测试集测试的模型一般都用训练集加评估集的数据一起训练，会有一定的涨点。我觉得可能是这个原因。

**Comment by duzijj** [comment]
> > 我用作者保存的训练好的ddrnet23-slim， 跑了cityscapes测试集，上传到官网，得到的结果是76.38， 而不是77.44， 是我漏掉了什么设置吗？有挺多模型都是这样得不到论文中的精度。
> 
> 我提供的模型是只在训练集上训练的模型，对应于在评估集上的结果。在测试集测试的模型一般都用训练集加评估集的数据一起训练，会有一定的涨点。我觉得可能是这个原因。

哈哈，好吧，那我也试试看。

**Comment by wuxiongni** [comment]
可以分享一下预训练的权重吗，我下载不了
