### ISSUE TITLE
关于辅助损失

### ISSUE THREAD

**Issue by FelixYHH** [ydhongHIT/DDRNet#35]
请问辅助损失使用的也是OHEM吗？貌似论文消融实验部分显示辅助损失没有提点效果？

**Comment by ydhongHIT** [comment]
> 请问辅助损失使用的也是OHEM吗？貌似论文消融实验部分显示辅助损失没有提点效果？

是。消融实验只是拿一个小模型再cityscapes上做了实验，确实没什么效果，不过因为辅助损失不会增加推理成本索性就用了。如果是在自己数据集使用的话，可以调整一下辅助损失的类型，比如不用ohem是不是会更好，或者换个其他的loss再或者改改权重什么的。
