### ISSUE TITLE
关于2080ti的推理速度

### ISSUE THREAD

**Issue by PGthree3** [ydhongHIT/DDRNet#37]
你好作者，我在2080ti上运行了您提供的测速代码，结果只有50多fps，请问这个正常吗，是设备问题还是其他

**Comment by ydhongHIT** [comment]
应该是不太正常，台式机2080Ti显卡测试的话速度怎么也得有90以上吧。也可能是你的设备有一定的问题，比如因为散热原因或者供电原因导致显卡功率不够。
