### ISSUE TITLE
SPP_super and Bottleneck_last

### ISSUE THREAD

**Issue by Zartris** [ydhongHIT/DDRNet#4]
Hi 

Going through your code, I cannot seem to find these two classes which are referred to in [DDRNET_39.py ](https://github.com/ydhongHIT/DDRNet/blob/main/segmentation/DDRNet_39.py)

These do not exist in the 23 versions so this might be a mistake?

**Comment by ydhongHIT** [comment]
> Hi
> 
> Going through your code, I cannot seem to find these two classes which are referred to in [DDRNET_39.py ](https://github.com/ydhongHIT/DDRNet/blob/main/segmentation/DDRNet_39.py)
> 
> These do not exist in the 23 versions so this might be a mistake?

You are right. I have corrected it, thanks.
