### ISSUE TITLE
A question about testset result

### ISSUE THREAD

**Issue by qifengluo** [ydhongHIT/DDRNet#5]
Hi, thanks for your share! when I trained the model on cityscapes using my train code. but The test results of the val set and the test set are much different，the val mIoU is close to the paper ,but the test set mIoU is very low,why ?

**Comment by ydhongHIT** [comment]
> Hi, thanks for your share! when I trained the model on cityscapes using my train code. but The test results of the val set and the test set are much different，the val mIoU is close to the paper ,but the test set mIoU is very low,why ?

Did you use images from val set for training?

**Comment by ydhongHIT** [comment]
> Hi, thanks for your share! when I trained the model on cityscapes using my train code. but The test results of the val set and the test set are much different，the val mIoU is close to the paper ,but the test set mIoU is very l

**Comment by qifengluo** [comment]
no,just the train set for training , need to use the train set + the val set  （2950+500 images ）for training?

**Comment by ydhongHIT** [comment]
> no,just the train set for training , need to use the train set + the val set （2950+500 images ）for training?

yes

**Comment by qifengluo** [comment]
OK ,thank you!
