### ISSUE TITLE
Apply on 256*256 input

### ISSUE THREAD

**Issue by zyXu1996** [ydhongHIT/DDRNet#7]
if the scale of input is 256*256, should I rescale it to a large size? Scale 1024*1024 or something.

**Comment by ydhongHIT** [comment]
Since ddrnet is designed for relatively high-resolution image segmentation, you should modify the number of downsampling branches in the dappm module.

**Comment by ydhongHIT** [comment]
> if the scale of input is 256_256, should I rescale it to a large size? Scale 1024_1024 or something.

Since ddrnet is designed for relatively high-resolution image segmentation, you should modify the number of downsampling branches in the dappm module.

**Comment by emregezer** [comment]
Hi,
how would you adjust the number of downsampling branches for samples of size 512x512?

**Comment by songbingyue** [comment]
> Hi, how would you adjust the number of downsampling branches for samples of size 512x512?

My image size is also 512x512. Have you solved this problem and how should I set dappm

**Comment by songbingyue** [comment]
> Hi, how would you adjust the number of downsampling branches for samples of size 512x512?

My image size is also 512x512. Have you solved this problem and how should I set dappm
