### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by Eddie-He-090** [ydhongHIT/DDRNet#9]
The baiduyun links of pre-trained models are dead!

**Comment by ydhongHIT** [comment]
> The baiduyun links of pre-trained models are dead!

Please use the googledrive link.

**Comment by wuxiongni** [comment]
> The baiduyun links of pre-trained models are dead!

could you share the pre-trained models?I can't download it from googledrive.thank you

**Comment by eddiehe99** [comment]
> could you share the pre-trained models?I can't download it from googledrive.thank you

I had downloaded DDRNet_39 and DDRNet_23_slim. Please send your email address to erheng.he@m.scnu.edu.cn if you want the pretrained models.
